"""Mutable in-memory data store for master-data and accounting client records.

Wraps the datasets generated by `app.fake_data` in process-lifetime mutable
state, exposed as plain module-level CRUD functions (not a class/singleton).
Existing routers read from this store instead of importing the static
generated lists directly, so admin-UI edits (and resets) are visible
immediately without restarting the process.

Data edits are in-memory only for the process lifetime; `reset()` regenerates
both datasets from scratch at the same cardinality `app.fake_data` produces
(18 master-data records, 8 accounting clients).
"""
from __future__ import annotations

import uuid
from dataclasses import replace
from typing import Any

from app.fake_data import (
    ACCOUNTING_CLIENTS,
    CLIENT_RESOURCES,
    _generate_accounting_clients,
    _generate_client_resources,
)
from app.models import Client, ClientResource


def _fresh_id() -> str:
    return str(uuid.uuid4())


_master_data: list[ClientResource] = list(CLIENT_RESOURCES)
_accounting_clients: list[Client] = list(ACCOUNTING_CLIENTS)


# --- master-data ---


def list_master_data() -> list[ClientResource]:
    return list(_master_data)


def add_master_data(fields: dict[str, Any]) -> ClientResource:
    payload = dict(fields)
    payload["Id"] = _fresh_id()
    record = ClientResource(**payload)
    _master_data.append(record)
    return record


def update_master_data(id: str, fields: dict[str, Any]) -> ClientResource:
    for index, record in enumerate(_master_data):
        if record.Id == id:
            updated = replace(record, **fields)
            _master_data[index] = updated
            return updated
    raise KeyError(id)


def delete_master_data(id: str) -> None:
    _master_data[:] = [record for record in _master_data if record.Id != id]


# --- accounting ---


def list_accounting_clients() -> list[Client]:
    return list(_accounting_clients)


def add_accounting_client(fields: dict[str, Any]) -> Client:
    payload = dict(fields)
    fresh_id = _fresh_id()
    payload["Id"] = fresh_id
    payload["ClientGuid"] = fresh_id
    record = Client(**payload)
    _accounting_clients.append(record)
    return record


def update_accounting_client(id: str, fields: dict[str, Any]) -> Client:
    for index, record in enumerate(_accounting_clients):
        if record.Id == id:
            updated = replace(record, **fields)
            _accounting_clients[index] = updated
            return updated
    raise KeyError(id)


def delete_accounting_client(id: str) -> None:
    _accounting_clients[:] = [record for record in _accounting_clients if record.Id != id]


# --- reset ---


def reset() -> None:
    """Restore both datasets together to a freshly generated dataset."""
    _master_data[:] = _generate_client_resources()
    _accounting_clients[:] = _generate_accounting_clients()
